language: generic

sudo: required
services:
  - docker

before_install: 
  - docker build -t pixerflame/react-test -f ./client/Dockerfile.dev

script:
  - docker run pixerflame/react-test npm test -- ----coverage
  - docker run -e CI=true pixerflame/react-test npm test

after_success: 
  - docker build -t pixerflame/multi-client -f ./client 
  - docker build -t pixerflame/multi-nginx -f ./nginx 
  - docker build -t pixerflame/multi-server -f ./server 
  - docker build -t pixerflame/multi-worker -f ./worker 
